### PR TITLE
Fixed subscribe form UI

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
The PR fixes #32 
I modified the UI to fix the reviews on #32
The current file path to the og and meta images are conflicting.
I modified the file paths on all respective pages.

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
@samswag @perriefidelis @Yomdroid I need MailChimp values to make the form work?

**Comment by samswag** [comment]
Thanks, I have reviewed the changes. I will also provide the script for the mailchimp

**Comment by BolajiAyodeji** [comment]
@samswag Alright, thank you!
Once the script action is provided, I'd activate the form.
Also, the success page UI has to be designed on MailChimp

**Comment by BolajiAyodeji** [comment]
@samswag @Yomdroid

**Comment by samswag** [comment]
Here 


<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://github.us17.list-manage.com/subscribe/post?u=2339b35e3ca4c86944e0601d0&amp;id=2dd17f603d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_2339b35e3ca4c86944e0601d0_2dd17f603d" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by BolajiAyodeji** [comment]
This is actually not what I need.
I just need the form action link?
We are not really using MailChimp's form, just their action and classes, that way we keep our design and do some redirects.

Here is what the link looks like:
`https://upnepa.us19.list-manage.com/subscribe/post?u=d9cfbfd60cd78101f81078bd1&amp;id=908fcec3d4`

**Comment by samswag** [comment]
https://github.us17.list-manage.com/subscribe/post?u=2339b35e3ca4c86944e0601d0&amp;id=2dd17f603d  this?

**Comment by BolajiAyodeji** [comment]
Here is a sample of a Subscription form I built.
Visit [upnepa.ng](https://upnepa.ng/), scroll to the footer section. That form was built from scratch but it uses MailChimp attributes.
Just test that form to see what we're looking at, thats exactly how it'd work.

**Comment by BolajiAyodeji** [comment]
> https://github.us17.list-manage.com/subscribe/post?u=2339b35e3ca4c86944e0601d0&amp;id=2dd17f603d this?

No, thats the link to MailChimp url or osca

**Comment by BolajiAyodeji** [comment]
What kind of form did you create, SignUp or Landing Page?

**Comment by BolajiAyodeji** [comment]
> https://github.us17.list-manage.com/subscribe/post?u=2339b35e3ca4c86944e0601d0&amp;id=2dd17f603d this?

Wait, let me try this. It should work!

**Comment by samswag** [comment]
Yes, I saw that. Can you give me 72 hours? Someone is working the MailChimp platform so we can use the current list instead of this one.

**Comment by BolajiAyodeji** [comment]
Alright @samswag 
Although I've sent two push just now, but once you have everything set, let me know so I fix it In.

**Comment by samswag** [comment]
Great thanks.

**Comment by BolajiAyodeji** [comment]
48hours late?

**Comment by BolajiAyodeji** [comment]
Hello?

**Pull request closed without merging**
