### PR TITLE
Fix typo 

### PR DESCRIPTION
**Pull request by Eronmmer**
I corrected some typographical and grammatical errors in the READMEs and some html files

### CODE REVIEW

**Review by BolajiAyodeji — APPROVED** [review]

**Review by BolajiAyodeji — APPROVED** [review]

**Comment by BolajiAyodeji** [comment]
Kindly fix merge conflicts please

**Comment by BolajiAyodeji** [comment]
Kindly fix all merge conflicts please

**Comment by Eronmmer** [comment]
Merge conflicts fixed 👍

**Comment by Eronmmer** [comment]
Done @BolajiAyodeji

**Review by BolajiAyodeji — APPROVED** [review]

**Pull request merged**
