### PR TITLE
Added Newsletter section to index page

### LINKED ISSUE #31: Build Newsletter Section on Index page
Add a simple subscribe form section to receive emails for newsletter.

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
This PR fixes #31 
image

Added placeholder to contact form also.
Fixed redundant blue borders around buttons when clicked resulting from bootstrap conflicts.

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
Right now, newsletter leads no where.
I need the link path to Mail Chimp subscriptions to complete the form process.
@samswag @perriefidelis @Kolokodess @Yomdroid

**Comment by samswag** [comment]
I just saw it. Some comments;
screenshot 2018-11-26 at 11 17 00 pm
screenshot 2018-11-26 at 11 16 52 pm

 1. The section for email is too long.
 2. It shouldn't be greater than the text secondly. 
 3. On the desktop view, the button should be on the right and not the left. The |  line differentiating between the social icons and mailchimp should be removed

**Comment by samswag** [comment]
@perriefidelis You can also comment

**Comment by BolajiAyodeji** [comment]
Okay;
For your first comment;
Being long does not really matter, have you seen other newsletters, its more longer than that, I used a `fill container` method and that section fills that entire column.
Second;
I'm using reusable styles, although I would work on that and reduce the form size plus make the button align on Desktop view.
Third; 
Those lines are custom with the styles, most of this features came with the original template and are attached to each other, like the page does not use bootstrap, it uses pure css, every grid was styled with that.
I would inspect to see what can be done also.

**Pull request closed without merging**
