### PR TITLE
Modified fonts and styles

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
Unified all fonts on all pages.
Fixed typo error in About-us page
Formatted codebase

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
🔥

**Comment by samswag** [comment]
The choice of fonts you used is having some clarity issues with my computer. I think people with low sight issues will have a hard time seeing anything. I suggest we look for another alternative

**Comment by BolajiAyodeji** [comment]
Alright @samswag

**Comment by BolajiAyodeji** [comment]
Would check for another. . 
Got any recommendations? @samswag

**Pull request closed without merging**
