### PR TITLE
Added A GetDate script to all Pages

### PR DESCRIPTION
**Pull request by ebube4im**
I noticed that the year on the site still had 2018. I don't know if that was deliberate. But I decided to add a script to update the current year. As part of my first contribution to open source

### CODE REVIEW

**Comment by samswag** [comment]
Thanks for the PR @ebube4im, @BolajiAyodeji can you please review?

**Review by BolajiAyodeji — CHANGES_REQUESTED** [review]
Please do this in the external script, inline scripts are not allowed!
You should be doing something like
```js
let copy = document.getElementById('copy');
let copyDate = new Date().getFullYear();
copy.innerHTML = copyDate;
```
Don't forget to style appopriately.
Good job!

**Comment by BolajiAyodeji** [comment]
Also, when sending multiple commits against one fix, your commit message should no longer be `added`, you're either `updating` or `modifying` except you're adding something new.

**Review by BolajiAyodeji — CHANGES_REQUESTED** [review]
- Your line spacing is too much.
- Why are you removing and fixing every part of the code? You should only be adding an ID to the footer, that's all.
- Why are you editing files that do not relate to your PR?
- Your line of code should be at the bottom of the script and not the top.

**Comment by BolajiAyodeji** [comment]
Your PR works fine, but fix all those.
Your edits would break the code!

**Comment by ebube4im** [comment]
Noted. Noticed that the lines spacing changes came from VS Code editor i used while making changes. Working in it.

**Comment by BolajiAyodeji** [comment]
@ebube4im are you still working on this?

**Comment by BolajiAyodeji** [comment]
I'll be closing this now, please reopen when you're ready to continue

**Pull request closed without merging**
