### PR TITLE
Fixed bugs in stylesheets & Bootstrap

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
Removed redundant classes.
Changed font and made it easy for a quick change of font with CDN and class name only.

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
@samswag I think this issue is to your eyes alone.
I don't find this font appealing to the eyes, neither do the creators.
I would send a fix using the most simplest font i can get or better still revert back.

**Comment by samswag** [comment]
Blue and white site with Bold text isn't a great combination. The size of the font is bigger or bolder than the previous one. @perriefidelis Maybe you want to comment. But again, I sent pictures showing what the new font is doing. Look at the "Twitter" and on About US page look at the description. I am using a MacBook with retina display to judge this.

**Comment by BolajiAyodeji** [comment]
We'd keep changing till you like it @samswag 
Do you like that one?

**Comment by samswag** [comment]
Keep changing isn't a good choice. Having a UI designer @perriefidelis bring up one with your suggestion is a good choice.

**Comment by BolajiAyodeji** [comment]
@samswag Yeah, thats true.
@perriefidelis is not really contributing to this tho

**Comment by BolajiAyodeji** [comment]
@samswag I made the fonts Light weight and similar to the Old one.
It should be fine now, Check?

**Comment by perriefidelis** [comment]
Hey Guys, sorry been off, been battling with my health. I suggested earlier that all the fonts should follow this. both all those in  block letters should be changed to small letters so it flows well 

screen shot 2018-11-11 at 5 06 47 pm

**Comment by BolajiAyodeji** [comment]
@perriefidelis Can you check what we have now?
Test this PR,
Its Light Weight already.
Better still, give us the font name of the font in that screenshot, we can't possibly determine the CDN from there.

**Comment by BolajiAyodeji** [comment]
@samswag review?
@perriefidelis ?

**Pull request merged**
