### PR TITLE
fixed bug in index header

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
Fixed alignment issue in header.

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
Now each page have different header stylings which is wrong.
We need to ensure resusability.
The introduction of Bootstrap adds some quick bugs, the community page looked properly aligned because it had bootstrap aligned, now if I fix the bug in the stylesheet, it fixes index.html only, community.html gets a new alignment due to BS classes.
We need to ensure reusability and avoid redundant classes

**Comment by samswag** [comment]
So can you fix 

"Now each page have different header stylings which is wrong.
We need to ensure resusability.
The introduction of Bootstrap adds some quick bugs, the community page looked properly aligned because it had bootstrap aligned, now if I fix the bug in the stylesheet, it fixes index.html only, community.html gets a new alignment due to BS classes.
We need to ensure reusability and avoid redundant classes"

**Comment by samswag** [comment]
I am away from my computer. I will review tomorrow

**Comment by BolajiAyodeji** [comment]
@samswag to fix that we need PHP or any equivalent.
we create markup and styles for the header and several other sections and call them when we need them that way we have same styles for each page.
Although this might be hard on this project because we already have a bulky css and some pages uses bootstrap.
So if we want to fix this perfectly, we might have to start the css from scratch.

**Comment by BolajiAyodeji** [comment]
@samswag what can Jekyll do?
You use it at sugar, do you use it to split pages?

**Comment by samswag** [comment]
> @samswag what can Jekyll do?
> You use it at sugar, do you use it to split pages?

Did you make your research about Jekyll?

**Pull request merged**
