### PR TITLE
added medium blog to menu

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
I added osca medium publication as Blog to the menu

image

### CODE REVIEW

**Comment by samswag** [comment]
Your PR have some conflict.

**Comment by samswag** [comment]
Too many changes on PR don't you think? Changing the text on the meta is a different

**Comment by BolajiAyodeji** [comment]
Yes, I'd continue on another PR.
Let me fix conflicts

**Comment by BolajiAyodeji** [comment]
@samswag fixed

**Pull request merged**
